# Generated by Django 6.0.5 on 2026-05-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='esgrecord',
            name='source',
        ),
        migrations.RemoveField(
            model_name='esgrecord',
            name='tenant',
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='normalized_unit',
            field=models.CharField(default='kg', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='normalized_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='scope',
            field=models.CharField(default='scope 1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
